[General]
AllowGrabBaseKeypad=true
AllowGrabBaseSpecial=false
AllowGrabLocks=false
AllowGrabMiscKeypad=true
AllowGrabMiscSpecial=true
MultipleActionsBehaviour=first
WindowSize=@Invalid()

[Super_L.1]
Comment=Afișează/Ascunde meniul principal
Enabled=true
path=/panel/fancymenu2/show_hide

[Alt%2BF2.2]
Comment=Afișează/ascunde dialogul lansatorului
Enabled=true
path=/runner/show_hide_dialog

[Control%2BAlt%2BD.3]
Comment=Afișează desktopul
Enabled=true
path=/panel/showdesktop/show_hide

[Meta%2BD.4]
Comment=Afișează desktopul
Enabled=true
path=/panel/showdesktop/show_hide

[Meta%2BE.5]
Comment=Managerul de fișiere
Enabled=true
Exec=pcmanfm-qt

[Control%2BAlt%2BT.6]
Comment=Terminal
Enabled=true
Exec=qterminal

[Print.7]
Comment=Captură de ecran
Enabled=true
Exec=lximage-qt, --screenshot

[Shift%2BControl%2BEscape.8]
Comment=Managerul de activități
Enabled=true
Exec=qps

[XF86AudioRaiseVolume.9]
Comment=Mărește volumul sunetului
Enabled=true
path=/panel/volume/up

[XF86AudioLowerVolume.10]
Comment=Micșorează volumul sunetului
Enabled=true
path=/panel/volume/down

[XF86AudioMute.11]
Comment=Oprește/pornește sunetul
Enabled=true
path=/panel/volume/mute

[Meta%2B1.12]
Comment=Activate task 1
Enabled=true
path=/panel/taskbar/task_1

[Meta%2B2.13]
Comment=Activate task 2
Enabled=true
path=/panel/taskbar/task_2

[Meta%2B3.14]
Comment=Activate task 3
Enabled=true
path=/panel/taskbar/task_3

[Meta%2B4.15]
Comment=Activate task 4
Enabled=true
path=/panel/taskbar/task_4

[Meta%2B5.16]
Comment=Activate task 5
Enabled=true
path=/panel/taskbar/task_5
