[General]
__userfile__=true

[panel1]
alignment=-1
animation-duration=0
background-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
background-image=
desktop=0
font-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
hidable=false
hide-on-overlap=false
iconSize=22
lineCount=1
lockPanel=true
opacity=100
panelSize=32
plugins=fancymenu2, quicklaunch, taskbar, tray, statusnotifier, kbindicator, volume, worldclock, showdesktop
position=Bottom
reserve-space=true
show-delay=0
visible-margin=true
width=100
width-percent=true

[fancymenu2]
alignment=Left
icon=/usr/share/lxqt/graphics/helix_1120.png
ownIcon=true
type=fancymenu

[quicklaunch]
alignment=Left
apps\1\desktop=/usr/share/applications/firefox-esr.desktop
apps\2\desktop=/usr/share/applications/pcmanfm-qt.desktop
apps\size=2
type=quicklaunch

[taskbar]
alignment=Left
type=taskbar

[tray]
alignment=Right
type=tray

[statusnotifier]
alignment=Right
type=statusnotifier

[kbindicator]
alignment=Right
keeper_type=global
layout_flag_pattern=
showLayout=true
show_caps_lock=false
show_layout=true
show_num_lock=false
show_scroll_lock=false
type=kbindicator

[volume]
alignment=Right
audioEngine=PulseAudio
ignoreMaxVolume=false
type=volume
volumeAdjustStep=3

[showdesktop]
alignment=Right
type=showdesktop

[worldclock]
alignment=Right
autoRotate=true
customFormat=
dateFormatType=short
dateLongNames=false
datePadDay=false
datePosition=after
dateShowDoW=false
dateShowYear=true
defaultTimeZone=
formatType=custom-timeonly
showDate=true
showTimezone=false
showTooltip=false
showWeekNumber=false
timeAMPM=false
timePadHour=false
timeShowSeconds=false
timeZones\size=0
timezoneFormatType=iana
timezonePosition=below
type=worldclock
useAdvancedManualFormat=false
